name: Deploy Cloud Function
on:
  push:
    branches: [ master ]
env:
  GAR_LOCATION: europe-west1 # TODO: update region of the Artifact Registry
  REPOSITORY: gcf # TODO: update to Artifact Registry docker repository
  IMAGE: hello-world-java-cf-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: hello-world-java-cf-actions
          runtime: java11
          project_id: modular-edge-357709
          region: europe-west1
          set_env_vars: REGION=europe-west1
          entry_point: com.example.Example

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding hello-world-java-cf-actions --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"

