name: Deploy Cloud Function
on:
  push:
    branches: [ master ]
env:
  GAR_LOCATION: europe-west1 # TODO: update region of the Artifact Registry
  REPOSITORY: gcf # TODO: update to Artifact Registry docker repository
  IMAGE: hello-world-java-cf-actions

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: access_token
          workload_identity_provider: 'projects/693845300997/locations/global/workloadIdentityPools/git-actions-pool/providers/git-provider'
          service_account: 'workload-identity-federation@modular-edge-357709.iam.gserviceaccount.com'

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0

      - name: deploy cloud function
        run: |
          gcloud functions deploy hello-world-java-cf-actions --region="europe-west1" --entry-point=com.example.Example --trigger-http --runtime=java11 --project=modular-edge-357709 --set-env-vars=REGION=europe-west1 --allow-unauthenticated
      
      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"
